In [1]:
import numpy as np
import pandas as pd
import import_ipynb
from utils import show

importing Jupyter notebook from utils.ipynb


In [2]:
df = pd.DataFrame({'key1':list('aabba'),
                   'key2':['one','two','one','two','one'],
                   'data1':np.random.randn(5),
                   'data2':np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one -0.945559  0.978327
1    a  two  0.945257 -1.484599
2    b  one  0.752178  0.261085
3    b  two -1.078760  1.046072
4    a  one -0.105603 -0.833717

In [3]:
grouped = df['data1'].groupby(df['key1'])
grouped

In [6]:
df = pd.DataFrame(np.arange(12).reshape((3,4)))
df

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [9]:
arr = df.values
show(arr)

<class 'numpy.ndarray'>
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
df.values[:] = arr.cumprod(axis=0)
show(df)

<class 'pandas.core.frame.DataFrame'>
--------------------
   0   1    2    3
0  0   1    2    3
1  0   5   12   21
2  0  45  120  231


In [12]:
arr = np.ones((4,4)) * 2.
show(arr)

<class 'numpy.ndarray'>
--------------------
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [13]:
arr.cumprod(axis=0)

array([[ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.],
       [16., 16., 16., 16.]])

In [18]:
df = pd.DataFrame(np.random.randn(20,12))


In [20]:
index = np.arange(0,22,2)

In [24]:
index[index.searchsorted([1,2,13,15,16,21],side='right') - 1]

array([ 0,  2, 12, 14, 16, 20])

In [217]:
data = np.array([1,2,3,4,4,5,2,5,6,7,8,11,21,23,24,3,8,9,11,21,21,22,23,45,56,77,88,100,3])

In [224]:
print(data)
def checkArray(arr,item):
    #arr = []
    if len(arr)==0 or arr[-1]<item:
        #arr = np.append(arr,item)
        arr.append(item)
    else:
        return False
    return len(arr)

dp = [[]]
for i,item in enumerate(data):    
    rst_1 = checkArray(dp[-1],item)
    #print(dp)
    if not rst_1 or i==len(data)-1:
        print('break ponit --->',item)
        print(dp)
        if len(dp) == 1:
            print('check1')
            dp.append([item])
            print(dp)
            #dp = np.append(dp,np.array(item))
            continue
        elif len(dp) == 2 and len(dp[0]) > len(dp[1]):
            print('check2')
            #dp = np.delete(dp,1)
            #dp = np.append(dp,np.array(item))
            dp.pop()
            dp.append([item])
            print(dp)
            continue
        else:
            print('check3')
            dp[0] = dp[1]
            dp.pop()
            dp.append([item])
            print(dp)
#print(dp)
                #dp = dp.delete(dp,1)
    #return dp[0], dp[0].size


[  1   2   3   4   4   5   2   5   6   7   8  11  21  23  24   3   8   9
  11  21  21  22  23  45  56  77  88 100   3]
break ponit ---> 4
[[1, 2, 3, 4]]
check1
[[1, 2, 3, 4], [4]]
break ponit ---> 2
[[1, 2, 3, 4], [4, 5]]
check2
[[1, 2, 3, 4], [2]]
break ponit ---> 3
[[1, 2, 3, 4], [2, 5, 6, 7, 8, 11, 21, 23, 24]]
check3
[[2, 5, 6, 7, 8, 11, 21, 23, 24], [3]]
break ponit ---> 21
[[2, 5, 6, 7, 8, 11, 21, 23, 24], [3, 8, 9, 11, 21]]
check2
[[2, 5, 6, 7, 8, 11, 21, 23, 24], [21]]
break ponit ---> 3
[[2, 5, 6, 7, 8, 11, 21, 23, 24], [21, 22, 23, 45, 56, 77, 88, 100]]
check2
[[2, 5, 6, 7, 8, 11, 21, 23, 24], [3]]


In [160]:
def NcheckArray(arr,i):  
    flag = True
    if len(arr)==0 or arr[-1]<i:
        #print(arr)
        arr = np.append(arr,i)
        #print(arr)
        
    else:
        #print('aflse')
        flag = False
    return flag,arr

e = np.empty(0)
for i in data:
    
    e = NcheckArray(e,i)
print(e)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [258]:
def longestRisingMonths(data):
    
    #print(data)
    
    def checkArray(arr,item):
        flag = True
        if arr.size == 0 or arr[-1]<item:
            arr = np.append(arr,item)
        else:
            flag = False
        return flag, arr

    dp = [np.empty(0)]
    for i,item in enumerate(data):    
        flag, dp[-1] = checkArray(dp[-1],item)        
        #rst = dp[-1].size
        #print(dp)
        #rst_1 = dp[-1].size if dp[-1] else False
        if not flag or i==len(data)-1:
            #print('break ponit --->',item)
            #print(dp)
            if len(dp) == 1:
                #print('check1')
                #dp.append(np.array(item))
                dp.append(np.array([item]))
                #print(dp)
                continue
            elif len(dp) == 2 and dp[0].size > dp[1].size:
                #print('check2')
                dp.pop()
                #dp = np.append(dp,np.array(item))
                dp.append(np.array([item]))
                #print(dp)
                #print('check2')
                continue
            else:
                #print('check3')
                dp[0] = dp[1]
                dp.pop()
                dp.append(np.array([item]))
                #print(dp)
    if len(dp) == 2 and len(dp[0]) >= len(dp[1]):
        dp.pop()
    return len(dp[0])

In [259]:
df = pd.DataFrame(np.random.rand(20,3))
df

0         1         2
0   0.569953  0.051518  0.455036
1   0.424419  0.091837  0.235047
2   0.561254  0.483366  0.600704
3   0.073074  0.457472  0.222524
4   0.797417  0.413782  0.967231
5   0.274347  0.397613  0.369039
6   0.577057  0.917296  0.877587
7   0.813558  0.980627  0.496341
8   0.684748  0.457909  0.995659
9   0.249262  0.310296  0.149910
10  0.152163  0.307394  0.537243
11  0.366674  0.076995  0.383119
12  0.373947  0.217525  0.532857
13  0.347813  0.926887  0.006892
14  0.617812  0.225902  0.619073
15  0.713171  0.497711  0.534335
16  0.686851  0.185676  0.457476
17  0.417560  0.858723  0.552149
18  0.521670  0.759018  0.137918
19  0.019140  0.529023  0.466812

In [260]:
dd = df.apply(longestRisingMonths,axis=0)

In [261]:
dd

0    3
1    3
2    2
dtype: int64