In [1]:
import numpy as np
import pandas as pd
import import_ipynb
from utils import show

importing Jupyter notebook from utils.ipynb


In [2]:
df = pd.DataFrame({'key1':list('aabba'),
                   'key2':['one','two','one','two','one'],
                   'data1':np.random.randn(5),
                   'data2':np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one -0.945559  0.978327
1    a  two  0.945257 -1.484599
2    b  one  0.752178  0.261085
3    b  two -1.078760  1.046072
4    a  one -0.105603 -0.833717

In [3]:
grouped = df['data1'].groupby(df['key1'])
grouped

In [6]:
df = pd.DataFrame(np.arange(12).reshape((3,4)))
df

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [9]:
arr = df.values
show(arr)

<class 'numpy.ndarray'>
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
df.values[:] = arr.cumprod(axis=0)
show(df)

<class 'pandas.core.frame.DataFrame'>
--------------------
   0   1    2    3
0  0   1    2    3
1  0   5   12   21
2  0  45  120  231


In [12]:
arr = np.ones((4,4)) * 2.
show(arr)

<class 'numpy.ndarray'>
--------------------
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [13]:
arr.cumprod(axis=0)

array([[ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.],
       [16., 16., 16., 16.]])

In [18]:
df = pd.DataFrame(np.random.randn(20,12))


In [20]:
index = np.arange(0,22,2)

In [24]:
index[index.searchsorted([1,2,13,15,16,21],side='right') - 1]

array([ 0,  2, 12, 14, 16, 20])

In [269]:
data = np.array([1,2,3,4,4,5,2,5,6,7,8,11,21,23,24,25,3,8,9,11,21,21,22,23,45,56,77,88,100,101,3])

In [270]:
print(data)
def checkArray(arr,item):
    #arr = []
    if len(arr)==0 or arr[-1]<item:
        #arr = np.append(arr,item)
        arr.append(item)
    else:
        return False
    return len(arr)

dp = [[]]
for i,item in enumerate(data):    
    rst_1 = checkArray(dp[-1],item)
    #print(dp)
    if not rst_1 or i==len(data)-1:
        print('break ponit --->',item)
        print(dp)
        if len(dp) == 1:
            print('check1')
            dp.append([item])
            print(dp)
            #dp = np.append(dp,np.array(item))
            continue
        elif len(dp) >= 2 and len(dp[0]) > len(dp[-1]):
            print('check2')
            #dp = np.delete(dp,1)
            #dp = np.append(dp,np.array(item))
            dp.pop()
            dp.append([item])
            print(dp)
            continue
        elif len(dp) >= 2 and len(dp[0]) == len(dp[-1]):
            dp.append([item])
            continue
        else:
            print('check3')
            dp = [dp[-1]]
            dp.append([item])
            print(dp)
if len(dp) >= 2 and len(dp[0]) >= len(dp[-1]):
    dp.pop()
print('----'*7)
print(dp)
#print(dp)
                #dp = dp.delete(dp,1)
    #return dp[0], dp[0].size


[  1   2   3   4   4   5   2   5   6   7   8  11  21  23  24  25   3   8
   9  11  21  21  22  23  45  56  77  88 100 101   3]
break ponit ---> 4
[[1, 2, 3, 4]]
check1
[[1, 2, 3, 4], [4]]
break ponit ---> 2
[[1, 2, 3, 4], [4, 5]]
check2
[[1, 2, 3, 4], [2]]
break ponit ---> 3
[[1, 2, 3, 4], [2, 5, 6, 7, 8, 11, 21, 23, 24, 25]]
check3
[[2, 5, 6, 7, 8, 11, 21, 23, 24, 25], [3]]
break ponit ---> 21
[[2, 5, 6, 7, 8, 11, 21, 23, 24, 25], [3, 8, 9, 11, 21]]
check2
[[2, 5, 6, 7, 8, 11, 21, 23, 24, 25], [21]]
break ponit ---> 3
[[2, 5, 6, 7, 8, 11, 21, 23, 24, 25], [21, 22, 23, 45, 56, 77, 88, 100, 101]]
check2
[[2, 5, 6, 7, 8, 11, 21, 23, 24, 25], [3]]
----------------------------
[[2, 5, 6, 7, 8, 11, 21, 23, 24, 25]]


In [160]:
def NcheckArray(arr,i):  
    flag = True
    if len(arr)==0 or arr[-1]<i:
        #print(arr)
        arr = np.append(arr,i)
        #print(arr)
        
    else:
        #print('aflse')
        flag = False
    return flag,arr

e = np.empty(0)
for i in data:
    
    e = NcheckArray(e,i)
print(e)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [290]:
df = pd.DataFrame(np.random.rand(20,3))
df

0         1         2
0   0.427837  0.024057  0.257237
1   0.340963  0.947700  0.171957
2   0.864447  0.918276  0.920881
3   0.500243  0.613480  0.469033
4   0.029446  0.329010  0.133331
5   0.140901  0.100676  0.102415
6   0.413597  0.345316  0.831204
7   0.411025  0.656960  0.360292
8   0.147237  0.739474  0.736568
9   0.432199  0.896934  0.038964
10  0.765190  0.326881  0.976921
11  0.989530  0.056919  0.253299
12  0.606848  0.368215  0.146831
13  0.626700  0.138316  0.375722
14  0.748014  0.625270  0.230577
15  0.576773  0.523323  0.796868
16  0.662801  0.045576  0.393394
17  0.746752  0.734019  0.486446
18  0.807752  0.969609  0.478255
19  0.161075  0.897647  0.096051

In [293]:
def longestRisingMonths(data):
    
    #print(data)
    
    def checkArray(arr,item):
        flag = True
        if arr.size == 0 or arr[-1]<item:
            arr = np.append(arr,item)
        else:
            flag = False
        return flag, arr

    dp = [np.empty(0)]
    for i,item in enumerate(data):    
        flag, dp[-1] = checkArray(dp[-1],item)        
        #rst = dp[-1].size
        #print(dp)
        #rst_1 = dp[-1].size if dp[-1] else False
        if not flag or i==len(data)-1:
            #print('break ponit --->',item)
            #print(dp)
            if len(dp) == 1:
                #print('check1')
                #dp.append(np.array(item))
                dp.append(np.array([item]))
                #print(dp)
                continue
            elif len(dp) >= 2 and dp[0].size > dp[-1].size:
                #print('check2')
                dp.pop()
                #dp = np.append(dp,np.array(item))
                dp.append(np.array([item]))
                #print(dp)
                #print('check2')
                continue
            elif len(dp) >= 2 and dp[0].size == dp[-1].size:
                dp.append(np.array([item]))
                continue
            else:
                #print('check3')
                dp = [dp[-1]]
                dp.append(np.array([item]))
                #print(dp)
    if len(dp) >= 2 and dp[0].size >= dp[-1].size:
        dp.pop()
    return dp

In [294]:
dd = df.apply(longestRisingMonths,axis=0)

In [322]:
show(dd)
show(dd[0])
show(dd[0][0])

<class 'pandas.core.series.Series'>
--------------------
0    [[0.14723677785743938, 0.43219913675882005, 0....
1    [[0.10067592102571021, 0.34531552056922366, 0....
2    [[0.1719568398565704, 0.9208810718172975], [0....
dtype: object
<class 'list'>
--------------------
[array([0.14723678, 0.43219914, 0.76519012, 0.9895302 ]), array([0.57677294, 0.66280095, 0.74675192, 0.80775213])]
<class 'numpy.ndarray'>
--------------------
[0.14723678 0.43219914 0.76519012 0.9895302 ]


In [396]:
_aa = np.array([1,2,3])
show(_aa)

<class 'numpy.ndarray'>
--------------------
[1 2 3]


In [397]:
_bb = np.row_stack((_aa,[4,5]))
show(_bb)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [307]:
vv = df.values
vv

array([[0.42783675, 0.02405728, 0.25723749],
       [0.34096268, 0.94770018, 0.17195684],
       [0.86444689, 0.91827614, 0.92088107],
       [0.50024261, 0.61348039, 0.46903335],
       [0.02944588, 0.32901038, 0.13333128],
       [0.14090084, 0.10067592, 0.1024154 ],
       [0.41359689, 0.34531552, 0.83120429],
       [0.41102504, 0.65695977, 0.3602915 ],
       [0.14723678, 0.73947432, 0.73656772],
       [0.43219914, 0.89693439, 0.03896387],
       [0.76519012, 0.32688057, 0.97692106],
       [0.9895302 , 0.05691932, 0.25329867],
       [0.60684754, 0.36821471, 0.14683052],
       [0.62670048, 0.13831613, 0.37572161],
       [0.74801398, 0.62527042, 0.23057689],
       [0.57677294, 0.52332332, 0.7968681 ],
       [0.66280095, 0.04557617, 0.39339369],
       [0.74675192, 0.73401894, 0.48644575],
       [0.80775213, 0.96960865, 0.47825483],
       [0.16107467, 0.89764733, 0.09605113]])

In [317]:
vvt = vv.T[0]
vvt

array([0.42783675, 0.34096268, 0.86444689, 0.50024261, 0.02944588,
       0.14090084, 0.41359689, 0.41102504, 0.14723678, 0.43219914,
       0.76519012, 0.9895302 , 0.60684754, 0.62670048, 0.74801398,
       0.57677294, 0.66280095, 0.74675192, 0.80775213, 0.16107467])

In [362]:
dp = np.empty((len(vv.T),1,1))
dp


array([[[2.16969204e-314]],

       [[2.16969204e-314]],

       [[2.16969204e-314]]])

In [363]:
show(dp[-1][-1])

<class 'numpy.ndarray'>
--------------------
[2.16969204e-314]


In [365]:
def _checkArray(arr,item):
    flag = True
    if arr.size <= 1 or arr[-1] < item:
        arr = np.append(arr,item)
    else:
        flag = False
    return flag, arr

dp = np.empty((len(vv.T),1,1))
for fundidx, fund in enumerate(vv.T):
    fund_array = dp[fundidx]
    for i, item in enumerate(fund):
        flag, fund_array[-1] = _checkArray(fund_array[-1], item)
        #rst = dp[-1].size
        #print(dp)
        #rst_1 = dp[-1].size if dp[-1] else False
        if not flag or i==len(fund)-1:
            print('break ponit --->',item)
            print(fund_array)
            if len(fund_array) == 1:
                print('check1')
                #dp.append(np.array(item))
                fund_array = np.row_stack((fund_array,item))
                print(dp)
                continue
            elif len(fund_array) >= 2 and fund_array[0].size > fund_array[-1].size:
                print('check2')
                fund_array = fund_array[:-1]
                fund_array = np.row_stack((fund_array,item))
                print(fund_array)
                continue
            elif len(fund_array) >= 2 and fund_array[0].size == fund_array[-1].size:
                print('check3')
                fund_array = np.row_stack((fund_array,item))
                continue
            else:
                print('check4')
                fund_array = fund_array[-1]
                fund_array = np.row_stack((fund_array,item))
                print(fund_array)
        

ValueError: setting an array element with a sequence.

In [417]:
dp = [np.empty(0)]

In [418]:
dp

[array([], dtype=float64)]

In [421]:
dp[-1] = np.append(dp[-1],np.array(123))
dp[-1]

array([123., 123., 123.])

In [423]:
dp = []
dp

[]

In [424]:
dp.append(np.empty(0))
dp

[array([], dtype=float64)]

In [430]:
dp[-1] = np.append(dp[-1],np.array([123]))
dp[-1]

array([123.])

In [429]:
dp.append(np.empty(0))
dp

[array([123., 123.]), array([], dtype=float64)]

In [431]:
dp

[array([123., 123.]), array([123.])]