In [1]:
import numpy as np
import pandas as pd
import import_ipynb
from utils import show

importing Jupyter notebook from utils.ipynb


In [87]:
a = np.random.randint(0,50,20)
pd.Series(a)

0     26
1      6
2     46
3     14
4     42
5     19
6      7
7      4
8     31
9     16
10    28
11     2
12     6
13     1
14    26
15    31
16    37
17    33
18    48
19    27
dtype: int64

In [108]:
shifted_a = a[1:]
shifted_a

array([ 6, 46, 14, 42, 19,  7,  4, 31, 16, 28,  2,  6,  1, 26, 31, 37, 33,
       48, 27])

In [109]:
shifted_a_zero = np.concatenate((shifted_a,[0]))
shifted_a_zero

array([ 6, 46, 14, 42, 19,  7,  4, 31, 16, 28,  2,  6,  1, 26, 31, 37, 33,
       48, 27,  0])

In [113]:
zero_range = (np.divide(shifted_a_zero,a) - 1)
zero_range = np.concatenate(([a[0]-1],zero_range))[:-1]
pd.Series(zero_range)

0     25.000000
1     -0.769231
2      6.666667
3     -0.695652
4      2.000000
5     -0.547619
6     -0.631579
7     -0.428571
8      6.750000
9     -0.483871
10     0.750000
11    -0.928571
12     2.000000
13    -0.833333
14    25.000000
15     0.192308
16     0.193548
17    -0.108108
18     0.454545
19    -0.437500
dtype: float64

In [118]:
def zero_run(data):
    #single_return = np.diff(np.concatenate(([1],data)))
    iszero = np.concatenate(([0],np.greater(data,0).view(np.int8),[0]))
    absdiff = np.abs(np.diff(iszero))
    lst_range = np.where(absdiff==1)[0].reshape(-1,2)
    #lst_range = np.where(absdiff>=0,_lst_range,0)
    return lst_range

In [119]:
zero_run(zero_range)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 17],
       [18, 19]])

In [61]:
_a = np.diff(a)
isrising = pd.Series(np.concatenate(([0],np.greater(_a,0).view(np.int8),[0])))
isrising

0     0
1     1
2     0
3     0
4     1
5     1
6     1
7     0
8     1
9     0
10    1
11    1
12    0
13    1
14    0
15    1
16    0
17    0
18    1
19    1
20    0
dtype: int64

In [65]:
absdiff = np.abs(np.diff(isrising))
pd.Series(absdiff)

0     1
1     1
2     0
3     1
4     0
5     0
6     1
7     1
8     1
9     1
10    0
11    1
12    1
13    1
14    1
15    1
16    0
17    1
18    0
19    1
dtype: int64

In [71]:
np.where(absdiff==1)[0].reshape(-1,2)+1

array([[ 1,  2],
       [ 4,  7],
       [ 8,  9],
       [10, 12],
       [13, 14],
       [15, 16],
       [18, 20]])

In [57]:
np.where(isrising==1)[0].reshape(-1,2)

ValueError: cannot reshape array of size 11 into shape (2)

In [50]:
iszero = np.concatenate(([0],np.greater(_a,0).view(np.int8),[0]))
absdiff = np.abs(np.diff(iszero))
lst_range = np.where(absdiff==1)[0].reshape(-1,2)
#lst_range = np.where(_lst_range>=0,_lst_range,0)

lst_range

array([[ 0,  1],
       [ 3,  6],
       [ 7,  8],
       [ 9, 11],
       [12, 13],
       [14, 15],
       [17, 19]])

In [2]:
def lst(data):
    single_return = np.diff(np.concatenate(([1],data)))
    iszero = np.concatenate(([0],np.greater(single_return,0).view(np.int8),[0]))
    absdiff = np.abs(np.diff(iszero))
    _lst_range = np.where(absdiff==1)[0].reshape(-1,2) - 1
    lst_range = np.where(_lst_range>=0,_lst_range,0)
    return lst_range

In [75]:
d = np.array([1,2,3,4,5])

In [84]:
_d = d[1:]
_d = np.append(_d,0)
_d

array([2, 3, 4, 5, 0])

In [85]:
np.divide(_d,d)

array([2.        , 1.5       , 1.33333333, 1.25      , 0.        ])

In [3]:
df = pd.DataFrame(np.random.uniform(0.,2.5,(20,5)),columns=list('ABCDE')).cumprod(axis=0)


A         B          C         D          E
0   2.530709e-01  0.501667   1.804457  0.033906   2.318310
1   7.696709e-04  0.124001   3.963391  0.019502   4.573844
2   5.002564e-06  0.237045   2.919523  0.030383   5.216478
3   7.138141e-06  0.452278   3.796723  0.013494  10.597336
4   3.467450e-06  0.318669   2.406447  0.010000  20.649390
5   5.174521e-06  0.104741   5.565516  0.016297  33.886710
6   3.503507e-06  0.062034  11.723785  0.029454  29.721471
7   1.676147e-06  0.096951   1.302208  0.014154  19.704909
8   3.177453e-06  0.061130   3.026362  0.016768   1.150109
9   1.029601e-06  0.148171   5.403135  0.039178   0.576257
10  1.011224e-07  0.162767  10.741385  0.032925   1.332520
11  2.877054e-08  0.271010  23.227157  0.014584   1.791633
12  1.567444e-08  0.243077  33.009283  0.014189   0.137251
13  1.343575e-08  0.395964   5.493599  0.028868   0.008669
14  1.442795e-08  0.857349  10.841246  0.034603   0.000788
15  2.123173e-08  2.025848  19.237886  0.022773   0.001068
16  7.963902e-10  0.275199  17.668440  0.046355   0.000787
17  1.804288e-09  0.462505  41.723032  0.033747   0.000021
18  1.389620e-09  0.430882  92.443223  0.042881   0.000008
19  7.702071e-10  1.054457  93.519735  0.043111   0.000004

In [86]:
a = df['A']
a

0     2.530709e-01
1     7.696709e-04
2     5.002564e-06
3     7.138141e-06
4     3.467450e-06
5     5.174521e-06
6     3.503507e-06
7     1.676147e-06
8     3.177453e-06
9     1.029601e-06
10    1.011224e-07
11    2.877054e-08
12    1.567444e-08
13    1.343575e-08
14    1.442795e-08
15    2.123173e-08
16    7.963902e-10
17    1.804288e-09
18    1.389620e-09
19    7.702071e-10
Name: A, dtype: float64

In [4]:
rst = []
for i,data in enumerate(df.T.values):
    fundname = df.columns[i]
    #print(fundname)
    #rst.append(pd.DataFrame(lst(data),columns=[[fundname,fundname],['start','end']]))
    single_rst = lst(data)
    rst.append(pd.DataFrame(single_rst,columns=[[fundname,fundname],['start','end']])) 

In [5]:
result = pd.concat(rst,axis=1,join='outer')
result

A           B         C         D         E      
  start   end start end start end start end start   end
0   2.0   3.0     1   3     0   1     1   2   0.0   5.0
1   4.0   5.0     6   7     2   3     4   6   9.0  11.0
2   7.0   8.0     8  11     4   6     7   9  14.0  15.0
3  13.0  15.0    12  15     7  12    12  14   NaN   NaN
4  16.0  17.0    16  17    13  15    15  16   NaN   NaN
5   NaN   NaN    18  19    16  19    17  19   NaN   NaN

In [6]:
result.columns.names= ['FUND','RANGE']
result.index.names=['idx']
result

FUND      A           B         C         D         E      
RANGE start   end start end start end start end start   end
idx                                                        
0       2.0   3.0     1   3     0   1     1   2   0.0   5.0
1       4.0   5.0     6   7     2   3     4   6   9.0  11.0
2       7.0   8.0     8  11     4   6     7   9  14.0  15.0
3      13.0  15.0    12  15     7  12    12  14   NaN   NaN
4      16.0  17.0    16  17    13  15    15  16   NaN   NaN
5       NaN   NaN    18  19    16  19    17  19   NaN   NaN

In [7]:
kk = result.diff(axis=1).stack()[::2]+1
kk

FUND         A    B    C    D    E
idx RANGE                         
0   end    2.0  3.0  2.0  2.0  6.0
1   end    2.0  2.0  2.0  3.0  3.0
2   end    2.0  4.0  3.0  3.0  2.0
3   end    3.0  4.0  6.0  3.0  NaN
4   end    2.0  2.0  3.0  2.0  NaN
5   end    NaN  2.0  4.0  3.0  NaN

In [10]:
mask = kk==np.max(kk,axis=0)
mask

FUND           A      B      C      D      E
idx RANGE                                   
0   end    False  False  False  False   True
1   end    False  False  False   True  False
2   end    False   True  False   True  False
3   end     True   True   True   True  False
4   end    False  False  False  False  False
5   end    False  False  False   True  False

In [18]:
range_df = result[mask]
range_df

FUND      A           B           C           D           E     
RANGE start   end start   end start   end start   end start  end
idx                                                             
0       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   0.0  5.0
1       NaN   NaN   NaN   NaN   NaN   NaN   4.0   6.0   NaN  NaN
2       NaN   NaN   8.0  11.0   NaN   NaN   7.0   9.0   NaN  NaN
3      13.0  15.0  12.0  15.0   7.0  12.0  12.0  14.0   NaN  NaN
4       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN
5       NaN   NaN   NaN   NaN   NaN   NaN  17.0  19.0   NaN  NaN

2.1231733746318052e-08

In [28]:
range_df['B'].dropna()

RANGE  start   end
idx               
2        8.0  11.0
3       12.0  15.0

In [35]:
for i in range_df['B'].dropna().index:
    show(i)

<class 'int'>
--------------------
2
<class 'int'>
--------------------
3


In [39]:
for i in range_df['B'].dropna().index:
    idx = i,
    start = range_df['B'].loc[i]['start']-1
    end = range_df['B'].loc[i]['end']
    print('{}:{}~{}'.format(i,start,end))

2:7.0~11.0
3:11.0~15.0


In [43]:
df['A'].loc[12]

1.567444419654387e-08

In [46]:
for fd in mask.columns:
    for i in range_df[fd].dropna().index:
        idx = i,
        _start = range_df[fd].loc[i]['start']
        start = _start -1 if _start != 0 else _start
        end = range_df[fd].loc[i]['end']
        value = df[fd].loc[end] / df[fd].loc[start] -1
        print('{}_{}:{}~{}--->{}'.format(fd,i,start,end,value))

A_3:12.0~15.0--->0.3545446001204646
B_2:7.0~11.0--->1.7953313427387134
B_3:11.0~15.0--->6.475167948141596
C_3:6.0~12.0--->1.8155824316117886
D_1:3.0~6.0--->1.1827094539358023
D_2:6.0~9.0--->0.3301412593023092
D_3:11.0~14.0--->1.3726604116350791
D_5:16.0~19.0--->-0.06997490249002425
E_0:0.0~5.0--->13.616988591005182


In [ ]:
_start,_end, nums = lst_range.loc[np.argmax(lst_range['LEN'])]
print(_start,_end, nums)
end = _end - 1
if _start == 0:
    start = 0
    max_return = cum_a[end]-1
else:
    start = _start
    max_return = cum_a[end] / cum_a[start] - 1
    print('max-return:',max_return)

nianhua = np.power((1+max_return),(12 / nums)) - 1
print('nianhua:',nianhua)


In [ ]:
cum_pda[2042:2057]

In [ ]:
nianhua = 