In [1]:
import numpy as np
import pandas as pd
import import_ipynb
from utils import show

importing Jupyter notebook from utils.ipynb


In [2]:
df = pd.DataFrame(np.random.rand(240, 50))

vv = df.values
#print(df.head)

print(vv)


[[0.25095687 0.92445193 0.54425956 ... 0.90198272 0.19658385 0.40974633]
 [0.83243058 0.24437008 0.93773094 ... 0.01352846 0.60501309 0.82428597]
 [0.36073227 0.50174665 0.99866034 ... 0.43549779 0.98610842 0.92813157]
 ...
 [0.10976623 0.6571842  0.26892237 ... 0.35978236 0.7114186  0.58721797]
 [0.29888914 0.22961891 0.5291497  ... 0.13032836 0.74145647 0.55499871]
 [0.65868896 0.69093627 0.23810014 ... 0.18701347 0.09346771 0.14218527]]


In [3]:
df.index = np.arange(20,260)
df

0         1         2         3         4         5         6   \
20   0.250957  0.924452  0.544260  0.510695  0.265512  0.795297  0.692323   
21   0.832431  0.244370  0.937731  0.000515  0.396148  0.941211  0.410715   
22   0.360732  0.501747  0.998660  0.927381  0.474664  0.442360  0.372569   
23   0.250228  0.050352  0.935466  0.683400  0.256490  0.977884  0.927398   
24   0.241971  0.103276  0.352733  0.676181  0.710468  0.037732  0.354865   
25   0.274877  0.720077  0.342382  0.691623  0.493584  0.919090  0.853530   
26   0.018744  0.418014  0.785387  0.579005  0.876173  0.832229  0.087130   
27   0.118195  0.671688  0.651121  0.791543  0.062121  0.068026  0.414951   
28   0.845650  0.121960  0.329490  0.354664  0.494166  0.456499  0.346612   
29   0.340540  0.107188  0.150170  0.686815  0.162682  0.215120  0.845705   
30   0.266804  0.642720  0.663041  0.321973  0.032564  0.496808  0.979298   
31   0.499178  0.467006  0.707274  0.164077  0.510969  0.508232  0.154901   
32   0.498011  0.832948  0.717652  0.819144  0.605847  0.002687  0.009217   
33   0.076344  0.260784  0.849671  0.487001  0.968250  0.315003  0.182854   
34   0.899789  0.809482  0.649185  0.004717  0.757994  0.885015  0.022364   
35   0.774126  0.693619  0.630695  0.408894  0.280533  0.492904  0.514187   
36   0.963468  0.468687  0.810678  0.878783  0.389218  0.615286  0.597844   
37   0.546811  0.997450  0.386349  0.637442  0.247664  0.387482  0.386186   
38   0.521233  0.144317  0.890489  0.213290  0.388066  0.607126  0.416358   
39   0.864468  0.776776  0.038408  0.874492  0.007671  0.747277  0.248521   
40   0.498481  0.551225  0.449141  0.121212  0.218794  0.886135  0.930003   
41   0.449387  0.811587  0.830624  0.758153  0.186912  0.917911  0.899544   
42   0.717553  0.004762  0.206708  0.993157  0.533921  0.591220  0.221735   
43   0.312071  0.366450  0.301146  0.995540  0.847553  0.943380  0.115502   
44   0.163762  0.223675  0.332286  0.280455  0.555564  0.700832  0.946641   
45   0.661014  0.897591  0.430735  0.189910  0.531707  0.060805  0.366910   
46   0.565000  0.731594  0.789636  0.674845  0.727066  0.291343  0.893846   
47   0.424754  0.166285  0.416916  0.500544  0.626293  0.172484  0.244953   
48   0.484055  0.424398  0.152274  0.425297  0.295221  0.777488  0.591201   
49   0.410536  0.054641  0.361437  0.134585  0.413501  0.320207  0.668898   
..        ...       ...       ...       ...       ...       ...       ...   
230  0.082096  0.065240  0.328717  0.001040  0.175950  0.570359  0.265954   
231  0.609127  0.513715  0.343694  0.422956  0.788187  0.525322  0.124762   
232  0.449537  0.088420  0.899455  0.679768  0.925076  0.086539  0.925483   
233  0.911958  0.614468  0.141120  0.562068  0.291911  0.696834  0.786287   
234  0.275418  0.877051  0.334338  0.623195  0.352902  0.493459  0.960818   
235  0.636532  0.418457  0.508622  0.317563  0.285640  0.904563  0.600052   
236  0.654090  0.954290  0.467459  0.620104  0.883573  0.609779  0.563993   
237  0.565104  0.332184  0.155578  0.193419  0.406857  0.719142  0.461567   
238  0.040967  0.989601  0.782461  0.645497  0.665084  0.868415  0.355502   
239  0.782358  0.189252  0.422470  0.331039  0.919213  0.898513  0.282722   
240  0.210618  0.629027  0.650160  0.661900  0.260412  0.741042  0.374192   
241  0.187970  0.488458  0.516402  0.983282  0.288531  0.309353  0.072310   
242  0.899762  0.400810  0.918976  0.054039  0.063468  0.447034  0.280260   
243  0.776629  0.763396  0.297836  0.634170  0.245010  0.467831  0.601993   
244  0.486130  0.909144  0.158430  0.827832  0.431277  0.038301  0.194425   
245  0.636544  0.169660  0.029822  0.212483  0.621194  0.344025  0.467668   
246  0.739743  0.365617  0.631594  0.526081  0.507968  0.965240  0.658276   
247  0.144082  0.818026  0.414043  0.534634  0.184162  0.517196  0.783224   
248  0.756171  0.453518  0.679798  0.073312  0.283630  0.056491  0.618508   
249  0.317181  0.620636  0.736271  0.626686  0.670130  0.823838  0.692254   
250  0.

In [4]:
def _checkArray(arr, item, datearr, dateidx):
    flag = True
    if len(arr) == 0 or arr[-1] < item:
        arr = np.append(arr, item)
        datearr = np.append(datearr, dateidx)
    # if arr.size == 1 and arr[0] == 0:
    #     arr[0] = item
    # elif arr.size == 1 and arr[0] < item:
    #     arr = np.append(arr,item)
    else:
        flag = False
    return flag, arr, datearr


In [5]:
for i,data in enumerate(vv.T):
    print(i)
    print(data)
    print('=====')
    
rst = []
timeline = []
for fundidx, data in enumerate(vv.T):
    #rst.append([np.empty(0)])
    dp = [np.empty(0)]
    do = [np.empty(0)]
    for i, item in enumerate(data):
        flag, dp[-1], do[-1] = _checkArray(dp[-1], item, do[-1], i)
        # rst = dp[-1].size
        # print(dp)
        # rst_1 = dp[-1].size if dp[-1] else False
        if not flag or i == len(data) - 1:
            print('break ponit @ {}--->{}'.format(i,item))
            print(dp)
            if len(dp) == 1:
                # print('check1--初始添加')
                # dp.append(np.array(item))
                dp.append(np.array([item]))
                do.append(np.array([i]))
                # print(dp)
                continue
            elif len(dp) >= 2 and dp[0].size > dp[-1].size:
                #print('check2--抛弃')
                dp.pop()
                do.pop()
                # dp = np.append(dp,np.array(item))
                dp.append(np.array([item]))
                do.append(np.array([i]))
                #print(dp)
                # print('check2')
                continue
            elif len(dp) >= 2 and dp[0].size == dp[-1].size:
                #print('check3--平行添加')
                dp.append(np.array([item]))
                do.append(np.array([i]))
                #print(dp)
                continue
            else:
                #print('check4--替换添加')
                dp = [dp[-1]]
                do = [do[-1]]
                dp.append(np.array([item]))
                do.append(np.array([i]))
                #print(dp)

    if len(dp) >= 2 and dp[0].size >= dp[-1].size:
        #print('来一次清理哟')
        dp.pop()
        do.pop()
        #print(dp)
    #print('循环{}---完成'.format(fundidx))
    rst.append(dp)
    timeline.append(do)
#     print('==='*9)
#     print(dp)
# print('======'*9)
# for fund in rst:
#     print(fund)
#return dp
print('====='*9)
# dt = zip(rst,timeline)
# for item in dt:
#     print(item)

0
[0.25095687 0.83243058 0.36073227 0.25022805 0.24197112 0.2748767
 0.01874402 0.11819536 0.84565036 0.3405401  0.266804   0.49917829
 0.49801145 0.07634363 0.89978941 0.77412623 0.96346811 0.54681094
 0.52123269 0.86446761 0.49848093 0.44938664 0.71755314 0.31207069
 0.16376239 0.66101355 0.56499973 0.4247538  0.48405493 0.4105363
 0.91635662 0.17318593 0.72838083 0.2670499  0.44341964 0.99612152
 0.64537008 0.69344924 0.7017453  0.47575719 0.78456324 0.96830058
 0.40599991 0.47733632 0.45776316 0.48531963 0.45825351 0.79908217
 0.24674765 0.72059317 0.67702838 0.92543895 0.7532137  0.30003346
 0.92367682 0.61265939 0.58043988 0.08666188 0.20311605 0.41972883
 0.04511267 0.9714859  0.76595245 0.83194226 0.22763043 0.46621022
 0.97739605 0.3822053  0.02728578 0.62787631 0.29853249 0.83103255
 0.45103021 0.35267657 0.33425889 0.13333992 0.98959776 0.95673244
 0.32713074 0.13628864 0.59951414 0.37647602 0.85146222 0.0409342
 0.23869611 0.65808078 0.87368374 0.62850393 0.05274826 0.00564

break ponit @ 72--->0.4510302134181253
[array([0.01874402, 0.11819536, 0.84565036]), array([0.2670499 , 0.44341964, 0.99612152]), array([0.64537008, 0.69344924, 0.7017453 ]), array([0.47575719, 0.78456324, 0.96830058]), array([0.08666188, 0.20311605, 0.41972883]), array([0.22763043, 0.46621022, 0.97739605]), array([0.29853249, 0.83103255])]
break ponit @ 73--->0.35267656784953716
[array([0.01874402, 0.11819536, 0.84565036]), array([0.2670499 , 0.44341964, 0.99612152]), array([0.64537008, 0.69344924, 0.7017453 ]), array([0.47575719, 0.78456324, 0.96830058]), array([0.08666188, 0.20311605, 0.41972883]), array([0.22763043, 0.46621022, 0.97739605]), array([0.45103021])]
break ponit @ 74--->0.33425889098309536
[array([0.01874402, 0.11819536, 0.84565036]), array([0.2670499 , 0.44341964, 0.99612152]), array([0.64537008, 0.69344924, 0.7017453 ]), array([0.47575719, 0.78456324, 0.96830058]), array([0.08666188, 0.20311605, 0.41972883]), array([0.22763043, 0.46621022, 0.97739605]), array([0.35267

[array([0.15017028, 0.66304097, 0.70727358, 0.71765218, 0.8496705 ]), array([0.20670791, 0.30114616, 0.33228584, 0.43073534, 0.78963595]), array([0.60080651, 0.70252802])]
break ponit @ 164--->0.2493949209202968
[array([0.15017028, 0.66304097, 0.70727358, 0.71765218, 0.8496705 ]), array([0.20670791, 0.30114616, 0.33228584, 0.43073534, 0.78963595]), array([0.46916646, 0.81612842])]
break ponit @ 165--->0.07951624902542453
[array([0.15017028, 0.66304097, 0.70727358, 0.71765218, 0.8496705 ]), array([0.20670791, 0.30114616, 0.33228584, 0.43073534, 0.78963595]), array([0.24939492])]
break ponit @ 168--->0.14107620697863354
[array([0.15017028, 0.66304097, 0.70727358, 0.71765218, 0.8496705 ]), array([0.20670791, 0.30114616, 0.33228584, 0.43073534, 0.78963595]), array([0.07951625, 0.19904547, 0.3340974 ])]
break ponit @ 170--->0.24532007370357145
[array([0.15017028, 0.66304097, 0.70727358, 0.71765218, 0.8496705 ]), array([0.20670791, 0.30114616, 0.33228584, 0.43073534, 0.78963595]), array([0.1

break ponit @ 186--->0.36611330776477957
[array([0.46686964, 0.66860518, 0.76125028, 0.82190775, 0.89020431]), array([0.20493587, 0.5100808 , 0.66480111, 0.89807142, 0.971519  ]), array([0.69113481])]
break ponit @ 188--->0.5396662908935287
[array([0.46686964, 0.66860518, 0.76125028, 0.82190775, 0.89020431]), array([0.20493587, 0.5100808 , 0.66480111, 0.89807142, 0.971519  ]), array([0.36611331, 0.89856868])]
break ponit @ 191--->0.7220506025740635
[array([0.46686964, 0.66860518, 0.76125028, 0.82190775, 0.89020431]), array([0.20493587, 0.5100808 , 0.66480111, 0.89807142, 0.971519  ]), array([0.53966629, 0.65818612, 0.82345781])]
break ponit @ 193--->0.7528871273413736
[array([0.46686964, 0.66860518, 0.76125028, 0.82190775, 0.89020431]), array([0.20493587, 0.5100808 , 0.66480111, 0.89807142, 0.971519  ]), array([0.7220506 , 0.86791993])]
break ponit @ 195--->0.04987690331425887
[array([0.46686964, 0.66860518, 0.76125028, 0.82190775, 0.89020431]), array([0.20493587, 0.5100808 , 0.6648011

break ponit @ 191--->0.7218575768302149
[array([0.18063567, 0.26369857, 0.30858613, 0.51460002, 0.87942465]), array([0.21867428, 0.50652259, 0.61520597, 0.64163738, 0.93546023]), array([0.03021576, 0.95901931])]
break ponit @ 194--->0.22715358897822313
[array([0.18063567, 0.26369857, 0.30858613, 0.51460002, 0.87942465]), array([0.21867428, 0.50652259, 0.61520597, 0.64163738, 0.93546023]), array([0.72185758, 0.75526094, 0.83316619])]
break ponit @ 196--->0.09296538540164234
[array([0.18063567, 0.26369857, 0.30858613, 0.51460002, 0.87942465]), array([0.21867428, 0.50652259, 0.61520597, 0.64163738, 0.93546023]), array([0.22715359, 0.23103711])]
break ponit @ 199--->0.41109398611342685
[array([0.18063567, 0.26369857, 0.30858613, 0.51460002, 0.87942465]), array([0.21867428, 0.50652259, 0.61520597, 0.64163738, 0.93546023]), array([0.09296539, 0.24729789, 0.61929093])]
break ponit @ 201--->0.000452264252883694
[array([0.18063567, 0.26369857, 0.30858613, 0.51460002, 0.87942465]), array([0.2186

[array([0.05784506, 0.17221347, 0.42522122, 0.47196653]), array([0.32153306, 0.35009445, 0.35958908, 0.48196591]), array([0.62759983, 0.8869791 ])]
break ponit @ 172--->0.13133079862696784
[array([0.05784506, 0.17221347, 0.42522122, 0.47196653]), array([0.32153306, 0.35009445, 0.35958908, 0.48196591]), array([0.79190012])]
break ponit @ 174--->0.27470237009720655
[array([0.05784506, 0.17221347, 0.42522122, 0.47196653]), array([0.32153306, 0.35009445, 0.35958908, 0.48196591]), array([0.1313308 , 0.41828876])]
break ponit @ 176--->0.22099216364519947
[array([0.05784506, 0.17221347, 0.42522122, 0.47196653]), array([0.32153306, 0.35009445, 0.35958908, 0.48196591]), array([0.27470237, 0.42091462])]
break ponit @ 179--->0.2613064653708467
[array([0.05784506, 0.17221347, 0.42522122, 0.47196653]), array([0.32153306, 0.35009445, 0.35958908, 0.48196591]), array([0.22099216, 0.33390903, 0.84306792])]
break ponit @ 182--->0.36992017473422834
[array([0.05784506, 0.17221347, 0.42522122, 0.47196653])

break ponit @ 221--->0.2937875568453536
[array([0.05336365, 0.07070069, 0.28827749, 0.64813353, 0.93076902,
       0.95704038]), array([0.54634866, 0.89156884])]
break ponit @ 224--->0.25600463283605823
[array([0.05336365, 0.07070069, 0.28827749, 0.64813353, 0.93076902,
       0.95704038]), array([0.29378756, 0.56914953, 0.86431707])]
break ponit @ 225--->0.0545008112997456
[array([0.05336365, 0.07070069, 0.28827749, 0.64813353, 0.93076902,
       0.95704038]), array([0.25600463])]
break ponit @ 227--->0.4829747491828167
[array([0.05336365, 0.07070069, 0.28827749, 0.64813353, 0.93076902,
       0.95704038]), array([0.05450081, 0.72427953])]
break ponit @ 229--->0.6735442074450944
[array([0.05336365, 0.07070069, 0.28827749, 0.64813353, 0.93076902,
       0.95704038]), array([0.48297475, 0.90168895])]
break ponit @ 231--->0.02691815435816647
[array([0.05336365, 0.07070069, 0.28827749, 0.64813353, 0.93076902,
       0.95704038]), array([0.67354421, 0.91157446])]
break ponit @ 235--->0.509

[array([0.17995034, 0.24066691, 0.52828234, 0.93781286]), array([0.17064317, 0.32791037, 0.52979418, 0.81099376]), array([0.21767073, 0.33558038, 0.3636405 , 0.71569788]), array([0.11925636, 0.24616206, 0.36185779, 0.88849382]), array([0.5774791 , 0.81224867, 0.94926044, 0.96732719]), array([0.43586347])]
break ponit @ 225--->0.4797597465589517
[array([0.17995034, 0.24066691, 0.52828234, 0.93781286]), array([0.17064317, 0.32791037, 0.52979418, 0.81099376]), array([0.21767073, 0.33558038, 0.3636405 , 0.71569788]), array([0.11925636, 0.24616206, 0.36185779, 0.88849382]), array([0.5774791 , 0.81224867, 0.94926044, 0.96732719]), array([0.33409322, 0.61648064])]
break ponit @ 227--->0.12081329773871463
[array([0.17995034, 0.24066691, 0.52828234, 0.93781286]), array([0.17064317, 0.32791037, 0.52979418, 0.81099376]), array([0.21767073, 0.33558038, 0.3636405 , 0.71569788]), array([0.11925636, 0.24616206, 0.36185779, 0.88849382]), array([0.5774791 , 0.81224867, 0.94926044, 0.96732719]), array([

break ponit @ 21--->0.4289109890088234
[array([0.12542278, 0.87209152]), array([0.40192722, 0.91378958]), array([0.29373969, 0.99725123]), array([0.09952399, 0.92286038]), array([0.53489612, 0.70101842]), array([0.13729167, 0.81108645]), array([0.37245345, 0.5917474 ]), array([0.50132614])]
break ponit @ 23--->0.19227205322538343
[array([0.12542278, 0.87209152]), array([0.40192722, 0.91378958]), array([0.29373969, 0.99725123]), array([0.09952399, 0.92286038]), array([0.53489612, 0.70101842]), array([0.13729167, 0.81108645]), array([0.37245345, 0.5917474 ]), array([0.42891099, 0.74120544])]
break ponit @ 26--->0.04880642628423637
[array([0.12542278, 0.87209152]), array([0.40192722, 0.91378958]), array([0.29373969, 0.99725123]), array([0.09952399, 0.92286038]), array([0.53489612, 0.70101842]), array([0.13729167, 0.81108645]), array([0.37245345, 0.5917474 ]), array([0.42891099, 0.74120544]), array([0.19227205, 0.47592581, 0.63129811])]
break ponit @ 30--->0.5970057025474351
[array([0.1922

[array([0.79199587, 0.83477439, 0.98013007]), array([0.21899835, 0.44689047, 0.85580074]), array([0.04823169, 0.15889927, 0.27552319]), array([0.07291306, 0.27825968, 0.65760938]), array([0.30189547, 0.57258557])]
break ponit @ 41--->0.010491379543836055
[array([0.79199587, 0.83477439, 0.98013007]), array([0.21899835, 0.44689047, 0.85580074]), array([0.04823169, 0.15889927, 0.27552319]), array([0.07291306, 0.27825968, 0.65760938]), array([0.07916593, 0.17418853])]
break ponit @ 45--->0.21698668196044668
[array([0.79199587, 0.83477439, 0.98013007]), array([0.21899835, 0.44689047, 0.85580074]), array([0.04823169, 0.15889927, 0.27552319]), array([0.07291306, 0.27825968, 0.65760938]), array([0.01049138, 0.10810007, 0.17311505, 0.5035168 ])]
break ponit @ 47--->0.1160755327023768
[array([0.01049138, 0.10810007, 0.17311505, 0.5035168 ]), array([0.21698668, 0.64488068])]
break ponit @ 50--->0.21151244376904887
[array([0.01049138, 0.10810007, 0.17311505, 0.5035168 ]), array([0.11607553, 0.2003

[array([0.70097009, 0.72223048, 0.82484826, 0.89202971]), array([0.21638382, 0.26989245, 0.52359258])]
break ponit @ 75--->0.6978875753390266
[array([0.70097009, 0.72223048, 0.82484826, 0.89202971]), array([0.02329415, 0.94057899])]
break ponit @ 77--->0.06860681118848344
[array([0.70097009, 0.72223048, 0.82484826, 0.89202971]), array([0.69788758, 0.71452361])]
break ponit @ 79--->0.4540427191978038
[array([0.70097009, 0.72223048, 0.82484826, 0.89202971]), array([0.06860681, 0.67412043])]
break ponit @ 80--->0.052855664115748935
[array([0.70097009, 0.72223048, 0.82484826, 0.89202971]), array([0.45404272])]
break ponit @ 83--->0.9562526082365578
[array([0.70097009, 0.72223048, 0.82484826, 0.89202971]), array([0.05285566, 0.84807551, 0.98494619])]
break ponit @ 84--->0.6344428288782173
[array([0.70097009, 0.72223048, 0.82484826, 0.89202971]), array([0.95625261])]
break ponit @ 85--->0.5614186951437541
[array([0.70097009, 0.72223048, 0.82484826, 0.89202971]), array([0.63444283])]
break po

break ponit @ 81--->0.34929336390220733
[array([0.15228982, 0.41628504, 0.76318283]), array([0.4145293 , 0.73802081, 0.74749475]), array([0.02361041, 0.67398   , 0.89103627]), array([0.40561186, 0.63578458, 0.98181737]), array([0.14277708, 0.49025053, 0.97105318]), array([0.93120697, 0.97849396, 0.98233699]), array([0.01735726, 0.20002794, 0.76656016]), array([0.36901169, 0.70975485, 0.7205811 ]), array([0.44413775, 0.57479631, 0.75750108, 0.85922181])]
break ponit @ 83--->0.7046181333587914
[array([0.44413775, 0.57479631, 0.75750108, 0.85922181]), array([0.34929336, 0.73959203])]
break ponit @ 85--->0.7211879810456818
[array([0.44413775, 0.57479631, 0.75750108, 0.85922181]), array([0.70461813, 0.95445593])]
break ponit @ 86--->0.37622248882480636
[array([0.44413775, 0.57479631, 0.75750108, 0.85922181]), array([0.72118798])]
break ponit @ 88--->0.7645330050820055
[array([0.44413775, 0.57479631, 0.75750108, 0.85922181]), array([0.37622249, 0.88760383])]
break ponit @ 89--->0.29524001308

[array([0.06049889, 0.12677972, 0.33303483, 0.79151489]), array([0.03546321, 0.46318078, 0.52187696, 0.95494491]), array([0.12099878, 0.34416773, 0.77716899, 0.9227155 ]), array([0.37991293, 0.58370598, 0.97160177])]
break ponit @ 111--->0.49631750533935814
[array([0.06049889, 0.12677972, 0.33303483, 0.79151489]), array([0.03546321, 0.46318078, 0.52187696, 0.95494491]), array([0.12099878, 0.34416773, 0.77716899, 0.9227155 ]), array([0.53998592])]
break ponit @ 112--->0.2844850633373146
[array([0.06049889, 0.12677972, 0.33303483, 0.79151489]), array([0.03546321, 0.46318078, 0.52187696, 0.95494491]), array([0.12099878, 0.34416773, 0.77716899, 0.9227155 ]), array([0.49631751])]
break ponit @ 114--->0.33228932580282566
[array([0.06049889, 0.12677972, 0.33303483, 0.79151489]), array([0.03546321, 0.46318078, 0.52187696, 0.95494491]), array([0.12099878, 0.34416773, 0.77716899, 0.9227155 ]), array([0.28448506, 0.37034686])]
break ponit @ 116--->0.8026874075421836
[array([0.06049889, 0.12677972

[array([0.02212413, 0.21340824, 0.24111352, 0.69550599]), array([0.28039716, 0.94284374])]
break ponit @ 97--->0.5949063936293605
[array([0.02212413, 0.21340824, 0.24111352, 0.69550599]), array([0.83266031])]
break ponit @ 98--->0.17824073633380755
[array([0.02212413, 0.21340824, 0.24111352, 0.69550599]), array([0.59490639])]
break ponit @ 100--->0.5226111603861968
[array([0.02212413, 0.21340824, 0.24111352, 0.69550599]), array([0.17824074, 0.80460053])]
break ponit @ 101--->0.04765329563385878
[array([0.02212413, 0.21340824, 0.24111352, 0.69550599]), array([0.52261116])]
break ponit @ 103--->0.5172657828392152
[array([0.02212413, 0.21340824, 0.24111352, 0.69550599]), array([0.0476533 , 0.83248727])]
break ponit @ 104--->0.24666822641860464
[array([0.02212413, 0.21340824, 0.24111352, 0.69550599]), array([0.51726578])]
break ponit @ 106--->0.5262051231239081
[array([0.02212413, 0.21340824, 0.24111352, 0.69550599]), array([0.24666823, 0.64255647])]
break ponit @ 107--->0.2412171345277481

break ponit @ 89--->0.6589720485269287
[array([0.17544715, 0.56362753, 0.8591189 , 0.91865369]), array([0.02189939, 0.16184963, 0.69759956, 0.75278088]), array([0.00914045, 0.7823485 ])]
break ponit @ 90--->0.6497506756377406
[array([0.17544715, 0.56362753, 0.8591189 , 0.91865369]), array([0.02189939, 0.16184963, 0.69759956, 0.75278088]), array([0.65897205])]
break ponit @ 91--->0.5597373948827381
[array([0.17544715, 0.56362753, 0.8591189 , 0.91865369]), array([0.02189939, 0.16184963, 0.69759956, 0.75278088]), array([0.64975068])]
break ponit @ 92--->0.12196151759527152
[array([0.17544715, 0.56362753, 0.8591189 , 0.91865369]), array([0.02189939, 0.16184963, 0.69759956, 0.75278088]), array([0.55973739])]
break ponit @ 94--->0.08305993597815098
[array([0.17544715, 0.56362753, 0.8591189 , 0.91865369]), array([0.02189939, 0.16184963, 0.69759956, 0.75278088]), array([0.12196152, 0.4500319 ])]
break ponit @ 95--->0.06192939939030462
[array([0.17544715, 0.56362753, 0.8591189 , 0.91865369]), a

break ponit @ 116--->0.0404305308674191
[array([0.00730724, 0.04720047, 0.13647648, 0.87936575, 0.89139589,
       0.97441045]), array([0.4918813 , 0.82751678])]
break ponit @ 119--->0.23600058874841456
[array([0.00730724, 0.04720047, 0.13647648, 0.87936575, 0.89139589,
       0.97441045]), array([0.04043053, 0.11599627, 0.6481614 ])]
break ponit @ 120--->0.14326980884659513
[array([0.00730724, 0.04720047, 0.13647648, 0.87936575, 0.89139589,
       0.97441045]), array([0.23600059])]
break ponit @ 124--->0.236286476583894
[array([0.00730724, 0.04720047, 0.13647648, 0.87936575, 0.89139589,
       0.97441045]), array([0.14326981, 0.26878678, 0.43707702, 0.46227512])]
break ponit @ 126--->0.3675930620809348
[array([0.00730724, 0.04720047, 0.13647648, 0.87936575, 0.89139589,
       0.97441045]), array([0.23628648, 0.81421133])]
break ponit @ 127--->0.2779898220300153
[array([0.00730724, 0.04720047, 0.13647648, 0.87936575, 0.89139589,
       0.97441045]), array([0.36759306])]
break ponit @ 1

break ponit @ 7--->0.3545253939701286
[array([0.18138575, 0.66364946]), array([0.49092013, 0.94250462]), array([0.37444094])]
break ponit @ 11--->0.2253037670352852
[array([0.18138575, 0.66364946]), array([0.49092013, 0.94250462]), array([0.35452539, 0.39741934, 0.53481432, 0.84169538])]
break ponit @ 14--->0.3960666091922672
[array([0.35452539, 0.39741934, 0.53481432, 0.84169538]), array([0.22530377, 0.56550943, 0.93576537])]
break ponit @ 17--->0.3292640175238525
[array([0.35452539, 0.39741934, 0.53481432, 0.84169538]), array([0.39606661, 0.43925165, 0.69545997])]
break ponit @ 19--->0.09411325503279178
[array([0.35452539, 0.39741934, 0.53481432, 0.84169538]), array([0.32926402, 0.84452996])]
break ponit @ 23--->0.9304939748219077
[array([0.35452539, 0.39741934, 0.53481432, 0.84169538]), array([0.09411326, 0.2649134 , 0.38410896, 0.96228218])]
break ponit @ 24--->0.5354726527255508
[array([0.35452539, 0.39741934, 0.53481432, 0.84169538]), array([0.09411326, 0.2649134 , 0.38410896, 0.

[array([0.02703582, 0.33492387, 0.43091022, 0.51984766]), array([0.07233799, 0.80668834, 0.88899172, 0.95032138]), array([0.52227437, 0.78480763])]
break ponit @ 170--->0.045059434164885226
[array([0.02703582, 0.33492387, 0.43091022, 0.51984766]), array([0.07233799, 0.80668834, 0.88899172, 0.95032138]), array([0.3978813])]
break ponit @ 172--->0.06718496520629547
[array([0.02703582, 0.33492387, 0.43091022, 0.51984766]), array([0.07233799, 0.80668834, 0.88899172, 0.95032138]), array([0.04505943, 0.78404824])]
break ponit @ 175--->0.45650927848703393
[array([0.02703582, 0.33492387, 0.43091022, 0.51984766]), array([0.07233799, 0.80668834, 0.88899172, 0.95032138]), array([0.06718497, 0.85885356, 0.932428  ])]
break ponit @ 176--->0.08775669822094301
[array([0.02703582, 0.33492387, 0.43091022, 0.51984766]), array([0.07233799, 0.80668834, 0.88899172, 0.95032138]), array([0.45650928])]
break ponit @ 178--->0.5775779272166627
[array([0.02703582, 0.33492387, 0.43091022, 0.51984766]), array([0.0

break ponit @ 226--->0.2887836172514646
[array([0.07053196, 0.64333503, 0.75486928, 0.80959852, 0.99854247]), array([0.02604655, 0.6696245 , 0.7052729 , 0.79298093, 0.79528515]), array([0.16040076, 0.23803055, 0.29893398, 0.61235793, 0.75658769]), array([0.37392304, 0.37782082, 0.42194493, 0.68831912, 0.94610641]), array([0.40719014])]
break ponit @ 227--->0.19647404393803358
[array([0.07053196, 0.64333503, 0.75486928, 0.80959852, 0.99854247]), array([0.02604655, 0.6696245 , 0.7052729 , 0.79298093, 0.79528515]), array([0.16040076, 0.23803055, 0.29893398, 0.61235793, 0.75658769]), array([0.37392304, 0.37782082, 0.42194493, 0.68831912, 0.94610641]), array([0.28878362])]
break ponit @ 232--->0.8547420704150237
[array([0.07053196, 0.64333503, 0.75486928, 0.80959852, 0.99854247]), array([0.02604655, 0.6696245 , 0.7052729 , 0.79298093, 0.79528515]), array([0.16040076, 0.23803055, 0.29893398, 0.61235793, 0.75658769]), array([0.37392304, 0.37782082, 0.42194493, 0.68831912, 0.94610641]), array(

break ponit @ 202--->0.3551180937980254
[array([0.30090911, 0.31665831, 0.45046137, 0.52948109, 0.82286384]), array([0.12719804, 0.42327348, 0.66952596, 0.73320379, 0.90510638]), array([0.02381143, 0.16056075, 0.90153056])]
break ponit @ 204--->0.44085997062852933
[array([0.30090911, 0.31665831, 0.45046137, 0.52948109, 0.82286384]), array([0.12719804, 0.42327348, 0.66952596, 0.73320379, 0.90510638]), array([0.35511809, 0.77371486])]
break ponit @ 205--->0.007514565358528125
[array([0.30090911, 0.31665831, 0.45046137, 0.52948109, 0.82286384]), array([0.12719804, 0.42327348, 0.66952596, 0.73320379, 0.90510638]), array([0.44085997])]
break ponit @ 208--->0.015497774737506576
[array([0.30090911, 0.31665831, 0.45046137, 0.52948109, 0.82286384]), array([0.12719804, 0.42327348, 0.66952596, 0.73320379, 0.90510638]), array([0.00751457, 0.42334842, 0.79204828])]
break ponit @ 210--->0.5503203545162882
[array([0.30090911, 0.31665831, 0.45046137, 0.52948109, 0.82286384]), array([0.12719804, 0.4232

[array([0.0914361 , 0.30497289, 0.69445776, 0.79391197, 0.83907423]), array([0.02679773, 0.06652066, 0.49786183, 0.77667735, 0.87405749]), array([0.17482908, 0.44972904, 0.83221214, 0.95510835])]
break ponit @ 201--->0.042481922794472826
[array([0.0914361 , 0.30497289, 0.69445776, 0.79391197, 0.83907423]), array([0.02679773, 0.06652066, 0.49786183, 0.77667735, 0.87405749]), array([0.25780847])]
break ponit @ 203--->0.9088545318073581
[array([0.0914361 , 0.30497289, 0.69445776, 0.79391197, 0.83907423]), array([0.02679773, 0.06652066, 0.49786183, 0.77667735, 0.87405749]), array([0.04248192, 0.96563102])]
break ponit @ 204--->0.08524725691441004
[array([0.0914361 , 0.30497289, 0.69445776, 0.79391197, 0.83907423]), array([0.02679773, 0.06652066, 0.49786183, 0.77667735, 0.87405749]), array([0.90885453])]
break ponit @ 207--->0.726827726519395
[array([0.0914361 , 0.30497289, 0.69445776, 0.79391197, 0.83907423]), array([0.02679773, 0.06652066, 0.49786183, 0.77667735, 0.87405749]), array([0.08

[array([0.06910265, 0.49098044, 0.5003091 ]), array([0.306871  , 0.70836365])]
break ponit @ 22--->0.03590200764906437
[array([0.06910265, 0.49098044, 0.5003091 ]), array([0.2034482 , 0.81404948])]
break ponit @ 24--->0.7020354418259233
[array([0.06910265, 0.49098044, 0.5003091 ]), array([0.03590201, 0.75407422])]
break ponit @ 26--->0.7267441326888373
[array([0.06910265, 0.49098044, 0.5003091 ]), array([0.70203544, 0.84675084])]
break ponit @ 27--->0.2779488483770145
[array([0.06910265, 0.49098044, 0.5003091 ]), array([0.72674413])]
break ponit @ 29--->0.27220649343483305
[array([0.06910265, 0.49098044, 0.5003091 ]), array([0.27794885, 0.56017416])]
break ponit @ 31--->0.47608707393727046
[array([0.06910265, 0.49098044, 0.5003091 ]), array([0.27220649, 0.72761858])]
break ponit @ 33--->0.11610344643975057
[array([0.06910265, 0.49098044, 0.5003091 ]), array([0.47608707, 0.53764101])]
break ponit @ 35--->0.6247817267731737
[array([0.06910265, 0.49098044, 0.5003091 ]), array([0.11610345,

[array([0.24326708, 0.48899609, 0.81724038, 0.93489449]), array([0.15753192, 0.28881456, 0.44239257, 0.57460627]), array([0.16803725, 0.46209967, 0.48755594, 0.94217407]), array([0.44181459, 0.65818626, 0.7648747 , 0.88363864])]
break ponit @ 170--->0.12172179531605887
[array([0.24326708, 0.48899609, 0.81724038, 0.93489449]), array([0.15753192, 0.28881456, 0.44239257, 0.57460627]), array([0.16803725, 0.46209967, 0.48755594, 0.94217407]), array([0.44181459, 0.65818626, 0.7648747 , 0.88363864]), array([0.08997929, 0.81666441])]
break ponit @ 173--->0.45242967321886285
[array([0.24326708, 0.48899609, 0.81724038, 0.93489449]), array([0.15753192, 0.28881456, 0.44239257, 0.57460627]), array([0.16803725, 0.46209967, 0.48755594, 0.94217407]), array([0.44181459, 0.65818626, 0.7648747 , 0.88363864]), array([0.1217218 , 0.27247793, 0.8055744 ])]
break ponit @ 174--->0.041517760287852146
[array([0.24326708, 0.48899609, 0.81724038, 0.93489449]), array([0.15753192, 0.28881456, 0.44239257, 0.57460627

[array([0.30562466, 0.36332835, 0.7930082 , 0.98437707]), array([0.52649105, 0.65832504])]
break ponit @ 72--->0.4170897189943198
[array([0.30562466, 0.36332835, 0.7930082 , 0.98437707]), array([0.45168068, 0.51994026])]
break ponit @ 74--->0.4041292039377107
[array([0.30562466, 0.36332835, 0.7930082 , 0.98437707]), array([0.41708972, 0.71037012])]
break ponit @ 77--->0.6329206195899986
[array([0.30562466, 0.36332835, 0.7930082 , 0.98437707]), array([0.4041292 , 0.57708128, 0.64031476])]
break ponit @ 78--->0.41218965539653096
[array([0.30562466, 0.36332835, 0.7930082 , 0.98437707]), array([0.63292062])]
break ponit @ 79--->0.36042387949565513
[array([0.30562466, 0.36332835, 0.7930082 , 0.98437707]), array([0.41218966])]
break ponit @ 81--->0.2562120807265381
[array([0.30562466, 0.36332835, 0.7930082 , 0.98437707]), array([0.36042388, 0.85651643])]
break ponit @ 84--->0.8470461171386172
[array([0.30562466, 0.36332835, 0.7930082 , 0.98437707]), array([0.25621208, 0.75132617, 0.85584058]

[array([0.00202676, 0.03793435, 0.44332846, 0.87875922]), array([0.24468903, 0.71234144, 0.72390977])]
break ponit @ 42--->0.04215609093926875
[array([0.00202676, 0.03793435, 0.44332846, 0.87875922]), array([0.01273289, 0.61844249, 0.92380239])]
break ponit @ 44--->0.16104894258145197
[array([0.00202676, 0.03793435, 0.44332846, 0.87875922]), array([0.04215609, 0.53523821])]
break ponit @ 46--->0.255878987473515
[array([0.00202676, 0.03793435, 0.44332846, 0.87875922]), array([0.16104894, 0.71756441])]
break ponit @ 49--->0.29337216031041913
[array([0.00202676, 0.03793435, 0.44332846, 0.87875922]), array([0.25587899, 0.25743722, 0.88898168])]
break ponit @ 51--->0.6719652309166185
[array([0.00202676, 0.03793435, 0.44332846, 0.87875922]), array([0.29337216, 0.91220731])]
break ponit @ 53--->0.35825407141928034
[array([0.00202676, 0.03793435, 0.44332846, 0.87875922]), array([0.67196523, 0.97551003])]
break ponit @ 57--->0.6343303487303658
[array([0.00202676, 0.03793435, 0.44332846, 0.87875

break ponit @ 3--->0.32258510579839716
[array([0.40974633, 0.82428597, 0.92813157])]
break ponit @ 4--->0.0680081521143252
[array([0.40974633, 0.82428597, 0.92813157]), array([0.32258511])]
break ponit @ 6--->0.4725372303938201
[array([0.40974633, 0.82428597, 0.92813157]), array([0.06800815, 0.81164845])]
break ponit @ 7--->0.30761323037028043
[array([0.40974633, 0.82428597, 0.92813157]), array([0.47253723])]
break ponit @ 8--->0.269541225130591
[array([0.40974633, 0.82428597, 0.92813157]), array([0.30761323])]
break ponit @ 12--->0.22253395866062342
[array([0.40974633, 0.82428597, 0.92813157]), array([0.26954123, 0.68274167, 0.82593059, 0.85214968])]
break ponit @ 14--->0.015656859808852897
[array([0.26954123, 0.68274167, 0.82593059, 0.85214968]), array([0.22253396, 0.76583076])]
break ponit @ 17--->0.33893716366915605
[array([0.26954123, 0.68274167, 0.82593059, 0.85214968]), array([0.01565686, 0.4174808 , 0.4482589 ])]
break ponit @ 18--->0.12096504357455229
[array([0.26954123, 0.682

In [6]:
rst

[[array([0.0409342 , 0.23869611, 0.65808078, 0.87368374]),
  array([0.36318867, 0.84471825, 0.89829016, 0.93952342])],
 [array([0.10580706, 0.14200485, 0.43867816, 0.68524943, 0.87050103]),
  array([0.0036253 , 0.53444865, 0.72915921, 0.93941405, 0.95564839])],
 [array([0.15017028, 0.66304097, 0.70727358, 0.71765218, 0.8496705 ]),
  array([0.20670791, 0.30114616, 0.33228584, 0.43073534, 0.78963595]),
  array([0.0097994 , 0.02515499, 0.524442  , 0.63997635, 0.88542604])],
 [array([0.12121171, 0.75815299, 0.9931565 , 0.9955404 ]),
  array([0.33089818, 0.55459113, 0.78234996, 0.82179885]),
  array([0.00725217, 0.04668537, 0.16122734, 0.68833958]),
  array([0.11499625, 0.50012047, 0.53709709, 0.89131135]),
  array([0.04021145, 0.12344755, 0.63323303, 0.85328179]),
  array([0.45825941, 0.54866103, 0.61422469, 0.64550993])],
 [array([0.46686964, 0.66860518, 0.76125028, 0.82190775, 0.89020431]),
  array([0.20493587, 0.5100808 , 0.66480111, 0.89807142, 0.971519  ])],
 [array([0.38748168, 0.607

In [7]:
timeline

[[array([83, 84, 85, 86]), array([182, 183, 184, 185])],
 [array([61, 62, 63, 64, 65]), array([125, 126, 127, 128, 129])],
 [array([ 9, 10, 11, 12, 13]),
  array([22, 23, 24, 25, 26]),
  array([185, 186, 187, 188, 189])],
 [array([20, 21, 22, 23]),
  array([84, 85, 86, 87]),
  array([147, 148, 149, 150]),
  array([155, 156, 157, 158]),
  array([166, 167, 168, 169]),
  array([198, 199, 200, 201])],
 [array([75, 76, 77, 78, 79]), array([80, 81, 82, 83, 84])],
 [array([17, 18, 19, 20, 21]),
  array([48, 49, 50, 51, 52]),
  array([199, 200, 201, 202, 203])],
 [array([93, 94, 95, 96, 97]), array([151, 152, 153, 154, 155])],
 [array([11, 12, 13, 14, 15]),
  array([89, 90, 91, 92, 93]),
  array([164, 165, 166, 167, 168]),
  array([226, 227, 228, 229, 230]),
  array([231, 232, 233, 234, 235])],
 [array([110, 111, 112, 113]), array([160, 161, 162, 163])],
 [array([53, 54, 55, 56, 57]), array([203, 204, 205, 206, 207])],
 [array([76, 77, 78, 79, 80, 81])],
 [array([219, 220, 221, 222, 223, 224])

In [8]:
tt = []
# daterst = [df.index[mask] for fund in timeline
#                           for mask in fund]
for fund in timeline:
    daterst = [df.index[mask] for mask in fund]
    tt.append(daterst)
tt

[[Int64Index([103, 104, 105, 106], dtype='int64'),
  Int64Index([202, 203, 204, 205], dtype='int64')],
 [Int64Index([81, 82, 83, 84, 85], dtype='int64'),
  Int64Index([145, 146, 147, 148, 149], dtype='int64')],
 [Int64Index([29, 30, 31, 32, 33], dtype='int64'),
  Int64Index([42, 43, 44, 45, 46], dtype='int64'),
  Int64Index([205, 206, 207, 208, 209], dtype='int64')],
 [Int64Index([40, 41, 42, 43], dtype='int64'),
  Int64Index([104, 105, 106, 107], dtype='int64'),
  Int64Index([167, 168, 169, 170], dtype='int64'),
  Int64Index([175, 176, 177, 178], dtype='int64'),
  Int64Index([186, 187, 188, 189], dtype='int64'),
  Int64Index([218, 219, 220, 221], dtype='int64')],
 [Int64Index([95, 96, 97, 98, 99], dtype='int64'),
  Int64Index([100, 101, 102, 103, 104], dtype='int64')],
 [Int64Index([37, 38, 39, 40, 41], dtype='int64'),
  Int64Index([68, 69, 70, 71, 72], dtype='int64'),
  Int64Index([219, 220, 221, 222, 223], dtype='int64')],
 [Int64Index([113, 114, 115, 116, 117], dtype='int64'),
  In

In [9]:
returns = []
for fundidx in range(len(tt)):
    returnc = []
    for lstidx in range(len(tt[fundidx])):
        prevtime = tt[fundidx][lstidx][0] -1
        prevdata = df.loc[prevtime][fundidx]
        lstdata = rst[fundidx][lstidx][-1]
        cumreturn = lstdata / prevdata - 1
        returnc.append(cumreturn)
    maxreturn = max(returnc)
    returns.append(maxreturn)

In [10]:
returns

[0.7351749963507654,
 6.170307231505057,
 1.5787414299629607,
 1.100437310383747,
 0.4555093093779756,
 6.098913076972618,
 3.1138970736537814,
 2.1578737791232903,
 0.1951401291147128,
 0.13211994276099714,
 4.401693241931291,
 1.9779245087034916,
 2.078131482297305,
 -0.016427916311067214,
 0.5136545828017083,
 2.0609725417822005,
 0.20624268632947818,
 2.3289515987289295,
 3.0113723754702537,
 4.389824445318222,
 0.2706347771499713,
 -0.17426460400598254,
 0.5769061140254788,
 5.769809883136942,
 0.6779789708083761,
 3.3099190431943715,
 3.7476696500366353,
 7.949535327402151,
 0.5947401209315406,
 1.9207894781672632,
 0.8772580101921343,
 0.7065631284452893,
 2.2424806559589374,
 7.88202230719231,
 0.8310489976721522,
 3.4650279113965787,
 4.678455928679085,
 1.2758846211087995,
 0.08896978956662038,
 0.623958122271344,
 0.24257554178902718,
 0.4290118375543681,
 3.355747233178618,
 2.0809112119621425,
 2.3462547178672546,
 3.0428399857090094,
 1.323538998626682,
 2.871076685684412